name: Build FlashPatch

on: [push, repository_dispatch, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build executable
        shell: powershell
        working-directory: FlashPatch
        run: >
          msbuild /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath=bin FlashPatch.csproj
      - name: Import certificate
        shell: bash
        working-directory: FlashPatch/bin
        run: >
          echo ${{ secrets.SIGN_WIN_CERT }} | base64 --decode > cert.pfx
      - name: Sign executable
        if: ${{ false }}
        shell: powershell
        working-directory: FlashPatch/bin
        run: >
          signtool sign /a /tr "${{ secrets.SIGN_WIN_TIMESTAMP }}" /td sha256 /fd sha256 /f cert.pfx /p "${{ secrets.SIGN_WIN_PASS }}" FlashPatch.exe
      - name: Remove certificate
        shell: bash
        working-directory: FlashPatch/bin
        run: >
          rm cert.pfx
      - uses: actions/upload-artifact@v4
        with:
          name: FlashPatch
          path: FlashPatch/bin/FlashPatch.exe
